steps:
- name: 'bash'
  args: 
  - echo
  - 'I am running in a pool with commit!'

# Install node_modules
- id: install-module
  name: 'gcr.io/cloud-builders/yarn'
  args: 
  - install

# Run unit test
- id: run-unit-test
  name: 'gcr.io/cloud-builders/yarn'
  args: 
  - test
  waitFor: [install-module]

# Build Nest App
- id: build-app
  name: 'gcr.io/cloud-builders/yarn'
  args: 
  - build
  waitFor: [install-module]

# Build container image
- id: build-docker-image
  name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-f',
   './Dockerfile',
   '-t',
   'asia-southeast1-docker.pkg.dev/fresh-weft-336116/nest-starter/nest-image:$COMMIT_SHA',
   '.'
  ]

# Push container image to Artifact Registry
- id: push-docker-image
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-southeast1-docker.pkg.dev/fresh-weft-336116/nest-starter/nest-image:$COMMIT_SHA

# Update Image Tags
- id: 'Setting App Image Tag'
  name: ubuntu
  args: ['bash','-c','sed -i "s,APP_IMAGE_NAME,asia-southeast1-docker.pkg.dev/fresh-weft-336116/nest-starter/nest-image:$COMMIT_SHA," k8s/deployment.yaml']

# Apply kubernetes files changed
- id: Apply k8s config changed
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

# Deploy container image to GKE
# - id: 'Push the image to cluster with the latest tag'
#   name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=k8s
#   - --image=asia-southeast1-docker.pkg.dev/fresh-weft-336116/nest-starter/nest-image:$COMMIT_SHA
#   - --location=asia-southeast1-a
#   - --cluster=cluster-1

images: [
  'asia-southeast1-docker.pkg.dev/fresh-weft-336116/nest-starter/nest-image:$COMMIT_SHA'
]
