apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-starter
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-starter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nest-starter
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: nest-starter
          image: APP_IMAGE_NAME
          imagePullPolicy: Always
          # command: ['sh', '-c', 'cp -r /app /srv; chown -R 82:82 /srv/app']
          # volumeMounts:
          # - name: code
          #   mountPath: /srv
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
      # volumes:
      #   - name: code
      #     emptyDir: {}
# https://stackoverflow.com/questions/51479556/what-is-best-method-to-update-image-tag-to-commit-sha-via-cloudbuilder