apiVersion: v1
kind: Service
metadata:
  name: nest-starter
  namespace: applications
  labels:
    app: nest-starter
spec:
  selector:
    app: nest-starter
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
